name: Rust CI/CD

on:
  push:
    branches: [ "testing" ]
  pull_request:
    branches: [ "staging" ]

env:
  CARGO_TERM_COLOR: always
  DATABASE_URL: postgresql://${{ secrets.POSTGRES_USER }}:${{ secrets.POSTGRES_PASSWORD }}@localhost:5432/${{ secrets.POSTGRES_DB }}

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create Superuser 
        run: |
          sudo useradd -m -d /home/${{ secrets.POSTGRES_USER }} -s /bin/bash ${{ secrets.POSTGRES_USER }}
          echo '${{ secrets.POSTGRES_USER }}:${{ secrets.POSTGRES_PASSWORD }}' | sudo chpasswd
          sudo adduser ${{ secrets.POSTGRES_USER }} sudo
          
      - name: Checkout Test Code
        uses: actions/checkout@v3
        with:
          repository: Harrysibbenga/TrackMyStuffApp
          ref: testing
          path: TrackMyStuffApp
          
      - name: Install nightly toolchain
        run: |
          rustup toolchain install nightly
          rustup default nightly
          rustup update
          
      - name: Install Diesel CLI
        run: |
          cargo install diesel_cli --no-default-features --features postgres
        working-directory: ./TrackMyStuffApp/track_my_stuff_api
        
      - name: Setup PostgreSQL
        uses: shogo82148/actions-setup-postgresql@v1
        with:
          postgresql-version: 'latest'
          database: ${{ secrets.POSTGRES_DB }}
          user: ${{ secrets.POSTGRES_USER }}
          password: ${{ secrets.POSTGRES_PASSWORD }}
        id: postgres
        
      - name: Build
        run: cargo build --verbose
        working-directory: ./TrackMyStuffApp/track_my_stuff_api
        
      - name: Run Diesel Migrations
        run: diesel migration run
        working-directory: ./TrackMyStuffApp/track_my_stuff_api
        
      - name: Run tests
        run: cargo test --verbose
        working-directory: ./TrackMyStuffApp/track_my_stuff_api
