name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: track_my_stuff_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
      working-directory: ./track_my_stuff_api
    - name: Setup Diesel CLI
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
        components: diesel_cli
    - name: Run Diesel Migrations
      run: diesel migration run
      working-directory: ./track_my_stuff_api
      env:
        DATABASE_URL: postgres://postgres:password@localhost:5432/track_my_stuff_test
    - name: Run tests
      run: cargo test --verbose
      working-directory: ./track_my_stuff_api
      env:
        DATABASE_URL: postgres://postgres:password@localhost:5432/track_my_stuff_test
        TEST_DATABASE_URL: postgres://postgres:password@localhost:5432/track_my_stuff_test
