name: Rust CI/CD

on:
  push:
    branches: [ "testing" ]
  pull_request:
    branches: [ "staging" ]

env:
  CARGO_TERM_COLOR: always
  DATABASE_URL: postgres://${{ secrets.POSTGRES_USER }}:${{ secrets.POSTGRES_PASSWORD }}@localhost:5432/${{ secrets.POSTGRES_DB }}

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v4
    - name: Create Superuser 
      run: |
        sudo useradd -m -d /home/${{ secrets.POSTGRES_USER }} -s /bin/bash ${{ secrets.POSTGRES_USER }}
        echo '${{ secrets.POSTGRES_USER }}:${{ secrets.POSTGRES_PASSWORD }}' | sudo chpasswd
        sudo adduser ${{ secrets.POSTGRES_USER }} sudo
        
    - name: Checkout Test Code
      uses: actions/checkout@v3
      with:
        repository: Harrysibbenga/TrackMyStuffApp
        ref: testing
        path: TrackMyStuffApp
        
    - name: Change Working Directory
      run: |
        cd TrackMyStuffApp/track_my_stuff_api
        
    - name: Install nightly toolchain
      run: |
        rustup toolchain install nightly
        rustup default nightly
        rustup update
        
    - name: Install Diesel CLI
      run: |
        cargo install diesel_cli --no-default-features --features postgres
        
    - name: Build
      run: cargo build --verbose
      
    - name: Create Database
      run: |
        sudo -u postgres psql -c "CREATE DATABASE ${{ secrets.POSTGRES_DB }};"
        sudo -u postgres psql -c "GRANT ALL PRIVILEGES ON DATABASE ${{ secrets.POSTGRES_DB }} TO ${{ secrets.POSTGRES_USER }};"
        
    - name: Run Diesel Migrations
      run: diesel migration run
      
    - name: Run tests
      run: cargo test --verbose
